### PR TITLE
Replace treetime submodule by treetime from conda

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

This PR replaces the submodule for treetime to use the treetime installed with conda:

- Remove the submodule
- Add treetime in conda environment
- Fix import of treetime

I ran the tests to check.

Bérénice

### CODE REVIEW

**Comment by bebatut** [comment]
@wdingx What do you think about this Pull Request? It would be helpful to make sure the Bioconda recipe will work correctly

**Comment by wdingx** [comment]
Thanks for this PR. I have already talked about it with Richard @rneher. He will take some time to consider it.

**Comment by rneher** [comment]
sorry for being slow here. I think we can remove treetime as a submodule along the lines @bebatut   suggests. At the time, treetime was very much in flux and a submodule ensured stability. @wdingx , could you test and merge this?

**Comment by wdingx** [comment]
@bebatut OK. I am currently on vacation and will work on it in the first week of March. Thanks.

**Comment by bebatut** [comment]
@wdingx Did you have the time to work on this pull request? We have a project using panx waiting for this fix 😄

**Comment by wdingx** [comment]
@bebatut  Yes. I tested this PR and it has passed the panX analysis pipeline. I am asking @rneher  to double-check it. If everything is fine, we will soon merge it. Thanks.

**Comment by wdingx** [comment]
@bebatut  I pushed a new branch. Please first use that for your project and let me know if you have any questions.
https://github.com/neherlab/pan-genome-analysis/tree/bebatut-remove_treetime

**Comment by bebatut** [comment]
@wdingx Thanks a lot!
Is it possible to get a release such that I can update the conda recipe? Thanks a lot!!!!

**Comment by wdingx** [comment]
Thanks. @bebatut v1.6.0 released

**Pull request merged**
